site:
  title: engDocMethod Example Engineering Documentation
  
  start_page: documentation:ROOT:index.adoc
content:
  sources:
    - url: https://github.com/M50505/engDocMethod-mb-SiteContentRoot.git
      start_path: docs
      branches:	[main]
      is_root: true
    - url: https://github.com/M50505/engDocMethod-mb-OrganizingPrinciples.git
      start_path: docs
      branches:	[main]
    - url: https://github.com/M50505/engDocMethod-mb-BuildAndPublish.git
      start_path: docs
      branches:	[main]
    - url: https://github.com/M50505/engDocMethod-mb-AuthoringTools.git
      start_path: docs
      branches:	[main]
    - url: https://github.com/M50505/engDocMethod-mb-SpecialWorkflows.git
      start_path: docs
      branches:	[main]
runtime:
  cache_dir: ./build/cache
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
urls:
  html_extension_style: indexify
asciidoc:
  extensions:
  - asciidoctor-kroki
antora:
  extensions:
  - require: '@antora/lunr-extension'
