site:
  title: engDocMethod Example Engineering Documentation
  
  start_page: documentation:ROOT:index.adoc
content:
  branches:	[main]
  sources:
    - url: https://github.com/M50505/engDocMethod-SiteContentRoot.git
      start_path: docs
    - url: https://github.com/M50505/engDocMethod-OrganizingPrinciples.git
      start_path: docs
    - url: https://github.com/M50505/engDocMethod-BuildAndPublish.git
      start_path: docs
    - url: https://github.com/M50505/engDocMethod-AuthoringTools.git
      start_path: docs
    - url: https://github.com/M50505/engDocMethod-SpecialWorkflows.git
      start_path: docs
runtime:
  cache_dir: ./build/cache
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
urls:
  html_extension_style: indexify
asciidoc:
  extensions:
  - asciidoctor-kroki
antora:
  extensions:
  - require: '@antora/lunr-extension'
